name: Bundle Release

on:
  # Run when a release is published
  release:
    types:
      - published

jobs:
  bundle-and-release:
    name: Bundle and release library
    runs-on: [ubuntu-24.04]
    permissions:
      contents: write # Used to upload the bundled library
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: prepare nix environment
        run: nix develop --command roc version

      - name: Bundle and release the library
        run: nix develop --command roc build --bundle .tar.br package/main.roc

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: 'package/*.tar.br'
          release_name: 'nightly'
          file_glob: true
