name: Check and Test Package
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  push:
    branches:
      - main

# this cancels workflows currently in progress if you start a new one
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build-and-test:
    runs-on: [ubuntu-24.04]
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: prepare nix environment
        run: nix develop --command roc version

      - name: roc check
        run: nix develop --command roc check package/main.roc

      - name: roc test
        run: nix develop --command roc test package/main.roc
